# Better Call CineCrew: Consistent Ultra-Long Narrative-to-Film Generation
# Paper: ECCV 2026
# Copyright (c) 2026 Sixun Dong
# Author: Sixun Dong
# Licensed under the Apache License, Version 2.0
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal
from .project_settings import ProjectSettings


# --- Visual Reference Schema (Phase 2: T2I Integration) ---
class VisualReferences(BaseModel):
    """Visual reference images for assets (character sheets, location establishing shots)"""
    canonical_image_path: Optional[str] = Field(
        None, 
        description="Path to canonical T2I-generated reference image"
    )
    generation_prompt: Optional[str] = Field(
        None,
        description="Prompt used to generate the reference image"
    )
    generation_params: Optional[Dict[str, Any]] = Field(
        None,
        description="T2I generation parameters (seed, steps, cfg_scale, model)"
    )
    validation_score: Optional[float] = Field(
        None,
        description="VLM validation score (0-1) indicating match with description"
    )
    generation_timestamp: Optional[str] = Field(
        None,
        description="ISO timestamp of image generation"
    )
    variations: List[str] = Field(
        default_factory=list,
        description="Paths to additional angle/lighting variations"
    )


class AudioReferences(BaseModel):
    """Character voice asset: after VoiceDesign's prompt is used to generate audio via TTS, the result is linked here to keep the voice consistent across dialogue."""
    voice_sample_path: Optional[str] = Field(
        None,
        description="Path to the voice sample generated by VoiceDesign → TTS (e.g. WAV), used for voice cloning / fixing the TTS voice"
    )
    voice_model_id: Optional[str] = Field(
        None,
        description="ID of a trained voice model (if TTS supports it); an alternative to or coexisting with voice_sample_path"
    )
    tts_config: Optional[Dict[str, Any]] = Field(
        None,
        description="TTS call parameters (e.g. engine, sample rate)"
    )


# --- 1. Character Asset - extended ---
class CharacterAsset(BaseModel):
    id: str = Field(..., description="Unique snake_case ID, e.g., char_michael_corleone")
    name: str = Field(..., description="Display name")

    # Visual
    description: str = Field(..., description="Physical appearance prompt for T2I models")
    clothing_style: str = Field(default="", description="Default outfit style and accessories")

    # Voice
    voice_preset_id: Optional[str] = Field(
        default=None,
        description="TTS preset ID (e.g. Seed-TTS). May coexist with voice_design; persisted via audio_references after audio is generated."
    )
    voice_description: str = Field(
        default="",
        description="(Optional) short voice description or for display; the initial voice is governed by voice_design, used to generate audio via TTS and then link to audio_references."
    )
    voice_design: Optional[str] = Field(
        default=None,
        description="TTS prompt generated by the VoiceDesign Agent (e.g. Qwen3-TTS 4-section form). Used to call TTS to produce the character's fixed voice; the generated voice file is linked to audio_references (voice_sample_path / voice_model_id). During dialogue, only emotion/tone is controlled and the voice is not regenerated."
    )

    # Inner - used to guide Action and micro-expressions
    personality: str = Field(default="", description="Personality traits (e.g., 'Ruthless, Loyal, Calculating')")
    backstory: str = Field(default="", description="Key background info that affects behavior and motivations")
    current_motivation: str = Field(default="", description="What does this character want in this script?")

    # Statistics
    scene_count: int = Field(default=0, description="How many scenes they appear in")
    dialogue_lines: int = Field(default=0, description="Estimated number of dialogue lines")
    key_relationships: List[str] = Field(default_factory=list, description="Related character IDs")
    
    # Phase 2: Visual References (T2I generated images)
    visual_references: Optional[VisualReferences] = Field(
        None,
        description="T2I-generated reference images for visual consistency"
    )
    
    # Phase 3: Audio References (Voice samples)
    audio_references: Optional[AudioReferences] = Field(
        None,
        description="Voice samples and TTS configuration"
    )

# --- 2. Location Asset - extended ---
class LocationAsset(BaseModel):
    id: str = Field(..., description="Unique ID, e.g., loc_int_dons_office")
    name: str = Field(..., description="Human-readable location name")
    type: Literal["INT", "EXT", "UNKNOWN"] = Field(..., description="Interior or Exterior")

    # Visual
    visual_style: str = Field(..., description="Lighting, atmosphere, texture prompts for keyframe generation")

    # Narrative
    narrative_function: str = Field(default="", description="Story purpose (e.g., 'Place of power', 'Safe haven', 'Confrontation space')")

    # Statistics
    time_of_day_stats: Dict[str, int] = Field(
        default_factory=dict, 
        description="Statistics of time usage, e.g., {'DAY': 2, 'NIGHT': 5}"
    )
    
    # Phase 2: Visual References (T2I generated images)
    visual_references: Optional[VisualReferences] = Field(
        None,
        description="T2I-generated establishing shots and reference images"
    )
    
    # Phase 3: Audio References (Ambient sounds)
    audio_references: Optional[AudioReferences] = Field(
        None,
        description="Ambient sound samples for the location"
    )
    usage_count: int = Field(default=0, description="How many times this location appears")

# --- 3. Prop Asset - new ---
class PropAsset(BaseModel):
    id: str = Field(..., description="Unique ID, e.g., prop_wine_glass")
    name: str = Field(..., description="Common name of the prop")
    related_character_id: Optional[str] = Field(
        None, 
        description="Primary character who uses this prop"
    )
    visual_description: str = Field(..., description="3D asset description for generation")
    importance: Literal["critical", "supporting", "background"] = Field(
        default="supporting",
        description="How important this prop is to the narrative (critical=plot essential, supporting=scene enhancement, background=ambient detail)"
    )
    usage_count: int = Field(default=0, description="How many times this prop appears")
    
    # Phase 2: Visual References (T2I generated images)
    visual_references: Optional[VisualReferences] = Field(
        None,
        description="T2I-generated product-style reference images"
    )

# --- 4. Narrative Context - new ---
class NarrativeContext(BaseModel):
    """Global narrative background, used to guide overall mood and style"""
    time_period: str = Field(..., description="When does the story take place (e.g., 'Summer 1945, post-WWII')")
    global_mood: str = Field(..., description="Overall emotional tone (e.g., 'Tense', 'Celebratory', 'Melancholic')")
    key_events: List[str] = Field(default_factory=list, description="Major plot points in this script segment")
    cultural_context: str = Field(default="", description="Cultural/historical background relevant to the story")

# --- 5. World Bible - master asset bundle ---
class AssetLibrary(BaseModel):
    """Complete world bible for a script"""
    project_title: str = Field(..., description="Project or script name")
    global_style: str = Field(..., description="Overall visual style guide")

    # Global settings - addresses the hallucination problem
    project_settings: Optional[ProjectSettings] = Field(
        None,
        description="Global constraints to prevent LLM hallucination and context drift"
    )

    # Narrative context (new)
    narrative_context: NarrativeContext = Field(..., description="Story background and context")

    # Assets
    characters: List[CharacterAsset] = Field(default_factory=list)
    locations: List[LocationAsset] = Field(default_factory=list)
    props: List[PropAsset] = Field(default_factory=list)
    
    def get_character_by_id(self, char_id: str) -> Optional[CharacterAsset]:
        """Helper method to retrieve character by ID"""
        for char in self.characters:
            if char.id == char_id:
                return char
        return None
    
    def get_location_by_id(self, loc_id: str) -> Optional[LocationAsset]:
        """Helper method to retrieve location by ID"""
        for loc in self.locations:
            if loc.id == loc_id:
                return loc
        return None
    
    def get_prop_by_id(self, prop_id: str) -> Optional[PropAsset]:
        """Helper method to retrieve prop by ID"""
        for prop in self.props:
            if prop.id == prop_id:
                return prop
        return None